Remove license check
LBPUnion/ProjectLighthouse pull request #1035
Opened 2024-06-19 22:19 UTC by jackcaver

It's quite annoying and doesn't really do anything, it can also trigger on people who didn't modify the source code.
It is also very easy to disable it by making a commit in the local repo or just by changing `IsDirty` to always return `true`

2024-06-22 20:48 UTC, sudokoko requested changes
https://github.com/LBPUnion/ProjectLighthouse/blob/be11e138f032ec306f9c732b4a3a3cee47740edc/ProjectLighthouse/Helpers/VersionHelper.cs#L22

This auto-property is unused and can be removed

2024-06-22 22:25 UTC, jackcaver commented
Technically it is still used by "version info" page, but sure, i can remove it, since that debug page only displays the value of this property

2024-06-22 22:46 UTC, sudokoko commented
Yes, that's fine. Just remove the part on the debug page too.

On Sat, Jun 22, 2024 at 6:25 PM jackcaver ***@***.***> wrote:

> Technically it is still used by "version info" page, but sure, i can
> remove it, since that debug page only displays the value of this property
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LBPUnion/ProjectLighthouse/pull/1035#issuecomment-2184214284>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQK7V5SOUMJ43RQ2HMWMWP3ZIX2VNAVCNFSM6AAAAABJSYXEP6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOBUGIYTIMRYGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-06-22 23:00 UTC, jackcaver commented
ok, removed it from those 2 places, is there anything else i need to change?

2024-06-22 23:14 UTC, sudokoko approved these changes

2024-06-23 00:17 UTC, Slendy approved these changes

2024-06-23 01:42 UTC, merged