Implement favouriting of developer levels
LBPUnion/ProjectLighthouse pull request #403
Opened 2022-08-05 13:51 UTC by TorutheRedFox

Fixes #398

NOTE: I kinda need help with getting the placeholder slots to get translated to an actual listing of developer slots, otherwise the game "forgets" you hearted the level upon restarting it.

2022-08-05 14:35 UTC, TorutheRedFox commented
I have no idea how LBP1 requests hearted levels

2022-08-05 14:57 UTC, TorutheRedFox commented
I need a packet capture for this stuff lol (but I can't find any except for a capture for vita from someone who hasn't hearted literally anything)

2022-08-05 17:14 UTC, TorutheRedFox commented
the server isn't even sending the slots across and idk why
great

2022-08-06 18:58 UTC, TorutheRedFox commented
like, is the query messed up or what?

2022-08-06 19:03 UTC, TorutheRedFox commented
ok so

-the slots are in the database
-the hearted slot list does have the developer slot in it
-the slot doesn't seem to be picked up by the query

2022-08-06 19:50 UTC, Slendy commented
It's because the current implementation uses ByGameVersion which adds a query so that only user slots are returned.

2022-08-06 20:17 UTC, TorutheRedFox commented
oh

well time to implement bygameversion for favourite levels lol

2022-08-06 20:58 UTC, TorutheRedFox commented
wow I can't believe I missed that lmao

I think I'm done here

2022-08-06 21:04 UTC, TorutheRedFox commented
![BCES00141_screenshot_2022_08_06_22_02_11](https://user-images.githubusercontent.com/15708278/183265947-bc051cc7-3956-4284-a1ad-6cd369cc6d31.png)

2022-08-06 21:17 UTC, TorutheRedFox commented
wait hold on, lbp2 levels still are broken

2022-08-06 21:23 UTC, TorutheRedFox commented
fixed it

2022-08-06 21:27 UTC, TorutheRedFox commented
the fix is pretty hacky but it gets the job done

2022-08-06 22:29 UTC, TorutheRedFox commented
actually thinking about it this probably would need a way to deal with dlc levels, but I don't know whether there's a way to actually distinguish between an LBP1 level or an LBP2 level

2022-08-07 10:47 UTC, TorutheRedFox commented
removed the sorting

the game can probably handle it itself

2022-08-08 10:22 UTC, TorutheRedFox commented
fixed #409 while I was at it

2022-08-09 14:50 UTC, TorutheRedFox commented
ok upon further research, the janky way of setting the level could theoretically work as you seemingly can't heart DLC levels in LBP1, but it'd cause issues with people modding LBP2 to get LBP1's story slots, so a hardcoded list of LBP1 story slots could theoretically work?

2022-08-09 15:33 UTC, TorutheRedFox commented
ok so what I'm doing right now is testing the hardcoded slot guids for LBP1 story levels, and better sorting of lolcatftw and favouriteSlots (with filter support)

2022-08-09 15:47 UTC, TorutheRedFox commented
if anyone wants to find the first slot guid for LBP2 you can go ahead

2022-08-09 15:51 UTC, TorutheRedFox commented
it seems to be g124806

2022-08-09 16:05 UTC, TorutheRedFox commented
ok it seems to work correctly

2022-08-10 20:33 UTC, TorutheRedFox commented
at this point might aswell call this general improvements as I've not only fixed up hearting developer levels but also the way hearted and queued levels in general are listed

2022-08-10 21:01 UTC, TorutheRedFox commented
damn I'm on a roll lol

I'm in the middle of implementing text filter for everything that the game supports it for lol

2022-08-10 21:16 UTC, TorutheRedFox commented
if anyone wants to know how my textfiltering implementation looks like, take a look at it on the main branch of my fork (https://github.com/TorutheRedFox/ProjectLighthouse/tree/main)

2022-08-11 15:08 UTC, TorutheRedFox commented
had to undeprecate HeartedProfileId as it's actually needed for proper sorting

2022-08-13 14:25 UTC, TorutheRedFox commented
hold on gotta rework some of this

2022-08-13 14:47 UTC, TorutheRedFox commented
fixed #430

2022-08-13 23:09 UTC, jvyden requested changes
Good work! There's a few issues I see mostly relating to duplicated code, but other than that it's just nitpicks.

2022-08-13 23:09 UTC, jvyden commented on ProjectLighthouse/PlayerData/Profiles/HeartedProfile.cs
> +    [Key] // this is actually useful for sorting
```suggestion
    [Key]
```

2022-08-13 23:09 UTC, jvyden commented on ProjectLighthouse.Servers.GameServer/Controllers/Slots/ListController.cs
> +        if (slotType == "developer") slot.GameVersion = slotGameVersion;
Also, 124806 should be a constant, `FirstLbp2DeveloperSlotId` or something.

2022-08-13 23:09 UTC, jvyden commented on ProjectLighthouse.Servers.GameServer/Controllers/Slots/ListController.cs
> +        if (slotType == "developer") slot.GameVersion = slotGameVersion;
Same as my other thread

2022-08-14 20:00 UTC, TorutheRedFox commented on ProjectLighthouse.Servers.GameServer/Controllers/Slots/ListController.cs
> +        PlayerData.GameVersion slotGameVersion = (slot.InternalSlotId < 124806) ? PlayerData.GameVersion.LittleBigPlanet1 : token.GameVersion;
that's some weird thing Visual Studio did that I didn't notice

2022-08-14 20:01 UTC, TorutheRedFox commented on ProjectLighthouse/Extensions/DatabaseExtensions.cs
> +
it also selects developer slots as ByGameVersion specifically excludes them

2022-08-14 20:11 UTC, TorutheRedFox commented on ProjectLighthouse/Extensions/DatabaseExtensions.cs
> +
thinking about it I can reduce it using an optional parameter

2022-08-14 20:15 UTC, TorutheRedFox commented on ProjectLighthouse/Extensions/DatabaseExtensions.cs
> +
ah looking back I did that already but forgot to remove the old function

2022-08-14 20:16 UTC, TorutheRedFox commented on ProjectLighthouse.Servers.GameServer/Controllers/Slots/ListController.cs
> +    private IQueryable<Slot> filterLolcatftwByRequest(string? gameFilterType, string? dateFilterType, GameVersion version, string username)
while reducing the functions into one this became unnecessary

2022-08-14 20:25 UTC, TorutheRedFox commented
ok I think it should be fine now

2022-08-14 20:33 UTC, jvyden reviewed
Code looks fine to me now; going to test in a bit and we'll go from there

2022-08-14 20:48 UTC, jvyden approved these changes
LGTM, thank you for your contribution!

2022-08-14 20:48 UTC, merged