StasticsHelper + Community Tab Performance Fix
LBPUnion/ProjectLighthouse pull request #713
Opened 2023-03-16 21:37 UTC by W0lf4llo

Hello! It's been a while since my last PR, I've been working on these fixes for a while as I was to lazy up until recently to actually fix these issues. The entire changelog is listed below!

- Total players online now show the exact amount of users playing said game, lets say there's 25 people online total, there's 5 playing LBP1, 10 playing LBP2, 5 playing Vita, and 5 playing LBP3. The game show you the amount of players playing the game you're currently on. So for LBP1 it'll show 5 total players online and so on!

- Team Picks total count now show the correct amount of levels that are able to be played on said game. I did a similar update to the total level count a while back as a test and seems to be working great! This update is similar, but it only affects the Team Pick total slot counts for game, this is very useful for vita players that want to actually see the amount of Team Picks that are on their server instance.

- Players in pod count, before when hovering over dive in it would show the total players online. Now it should display the amount of users that you're able to dive into, unfortunately I don't really know of a way to differentiate between PSN and RPCN users. If i do eventually find out I'll submit another PR fixing that issue!

- LBP3 Community Tab Performance Update, Yup, the LBP3 Community Tab should now be much smoother than before due to the "IEnumerable"'s changed to "IQueryable" Thanks to @sudokoko for this fix!

Special thanks to @Slendy, @daggintosh, & @sudokoko for making this all possible.

2023-03-16 21:40 UTC, sudokoko commented
Hi there, thank you for your Project Lighthouse contribution. If you could sync your branch with upstream that would be awesome :)

2023-03-16 21:51 UTC, sudokoko requested changes
1 minor nitpick but otherwise LGTM. Feel free to commit the change and I'll approve

2023-03-16 21:51 UTC, sudokoko commented on ProjectLighthouse/Types/Entities/Level/Slot.cs
> +
```suggestion
```
Remove unnecessary whitespace/tab

2023-03-16 21:57 UTC, sudokoko approved these changes
LGTM

2023-03-16 23:05 UTC, daggintosh commented
Insert nitpick

2023-03-17 03:33 UTC, Slendy requested changes
Just one small change related to reusing a GetToken call

2023-03-17 03:33 UTC, Slendy commented on ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs
> +        int total = await StatisticsHelper.TeamPickCountForGame(this.database, this.GetToken().GameVersion);
```suggestion
        int total = await StatisticsHelper.TeamPickCountForGame(this.database, token);
```
Token already exists in the current context so there's no need to call GetToken again

2023-03-17 03:38 UTC, daggintosh approved these changes
if this check fails you're fired

2023-03-17 03:40 UTC, daggintosh commented
@Slendy you're fired.

2023-03-17 03:43 UTC, sudokoko commented on ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs
> +        int total = await StatisticsHelper.TeamPickCountForGame(this.database, token);
```suggestion
        int total = await StatisticsHelper.TeamPickCountForGame(this.database, token.GameVersion);
```

Slendy was wrong

2023-03-17 03:48 UTC, Slendy approved these changes

2023-03-17 03:54 UTC, merged