Extend slot badges to display team pick and level warning badges
LBPUnion/ProjectLighthouse pull request #764
Opened 2023-05-14 12:02 UTC by sudokoko

This PR extends [ProjectLighthouse.Servers.Website/Extensions/FormattingExtensions.cs](https://github.com/LBPUnion/ProjectLighthouse/blob/5e084001705e00e6675abbc8bc7569c4d353d7c0/ProjectLighthouse.Servers.Website/Extensions/FormattingExtensions.cs) to be able to display badges for levels that are team picked and for levels that have warnings.

Warnings that will be able to be displayed include:
* `Lbp1Only` (This level is designed for LittleBigPlanet 1 only.)
* `CrossControllerRequired` (This level is designed to be played in Cross-Controller mode.)
* `MoveRequired` (This level requires a PlayStation Move controller.)

> **Warning** Anybody using Docker to run ProjectLighthouse will need to completely rebuild the image in order to apply the new stylesheet changes, as Docker caches the initial CSS the first time you build it.

2023-05-14 18:07 UTC, daggintosh commented on ProjectLighthouse.Servers.Website/Extensions/FormattingExtensions.cs
> +        };
```suggestion
        {
            {
                Lbp1Only: true,
            } => "This level can be played via LBP 1 only.",
            {
                CrossControllerRequired: true,
            } => "This level requires the LBP2: Cross-Controller DLC and companion app.",
            {
                MoveRequired: true,
            } => "This level requires a PlayStation Move controller.",
            _ => "",
        };
```
you dont need to follow this directly but we should make it a bit more brief and remove direct references to Sony's trademarks.

2023-05-14 18:11 UTC, daggintosh approved these changes
I have been responded to with "L+Ratio" and have revised my review.

2023-05-14 20:05 UTC, Slendy requested changes

2023-05-14 20:05 UTC, Slendy commented on ProjectLighthouse.Servers.Website/Extensions/FormattingExtensions.cs
> +        slot.Lbp1Only || slot.CrossControllerRequired || slot.MoveRequired ? "ui orange icon exclamation circle" : "";
Since you are relying on html title tags, this implementation doesn't translate well to mobile. You may need to create more descriptive icons.

2023-05-14 20:05 UTC, Slendy commented on ProjectLighthouse.Servers.Website/Extensions/FormattingExtensions.cs
> +    // ReSharper disable once UnusedParameter.Global
```suggestion
```
I don't think this is needed

2023-05-15 12:55 UTC, sudokoko commented
Converting this to a draft state while I sit on a few icon related things.

2023-05-23 03:03 UTC, closed without merging